{
    "users":[
        {
            "firstName":"Chudamani",
            "lastName":"Lawrence",
            "age":20,
            "email":"cmlowerence@gmail.com"
        },
        {
            "firstName":"Rishi",
            "lastName":"Rathour",
            "age":20,
            "email":"rishirathour123@gmail.com"
        },
        {
            "firstName":"Virender",
            "lastName":"Kumar",
            "age":21,
            "email":"virenderkumar123@gmail.com"
        }
    ]
}